Add remove task
gabrie-lhilarion/minimalist pull request #4
Opened 2021-12-04 23:06 UTC by gabrie-lhilarion

I added ability to add, delete and update a task
To edit/update a task click on the task description text

2021-12-04 23:30 UTC, henatan99 requested changes
Hi @gabrie-lhilarion , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 23:30 UTC, henatan99 commented on src/data.js
> +  }
- [ ] When I check a todo item after the first batch of todo items are created, it updates the completed status of the next todo item in the local storage. But after page refresh, it works perfectly. I think you have an indexing problem when the page loads initially. Kindly fix this issue. :pray: 

![Screenshot from 2021-12-05 02-15-27](https://user-images.githubusercontent.com/64894927/144727563-7b9bebeb-f77f-4bc2-a2e4-17147591efe9.png)

2021-12-08 06:47 UTC, rloterh requested changes
Hi Gabriel, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- CRUD function is working as intended
- Good ReadMe
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 06:47 UTC, rloterh commented on src/ui.js
> +      .map((task, index) => `
- [ ] New entries **do not match** the property index. The _property index_ must be set to the value of the _new array length_ (i.e. if a 5th task is added to the list, the index of that task should equal 5). Kindly ensure to improve upon this aspect

**Index mismatch:**
![image](https://user-images.githubusercontent.com/12745474/145161024-ed11dffc-65a2-4557-b439-d47b336200b3.png)

2021-12-08 06:47 UTC, rloterh commented on src/handlers.js
> +    // afterAddNew.forEach((item, index) => { item.index = index; });
- [ ] Kindly remove commented code, so as to make your code base well organized

2021-12-08 08:21 UTC, gabrie-lhilarion commented
# CORRECTED

- Indexing error pointed out by the last reviewer orrected

2021-12-08 08:33 UTC, dasileker approved these changes
## **Hi @gabrie-lhilarion,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 09:01 UTC, merged